Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.CookieConsent: true

KaufmannDigital:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    type: ''

    #Global configuration of PolicyPage
    policyPageNode: 'needs-to-be-set' #UUID of global page you want to link

    # #Configuration per site for multisite installations
    # #Replace site1/site2 with your sitename (/sites/sitename/node-a2ufd/.../)
    # policyPageNodes:
    #   site1: 'c7a91aa8-fbac-4c24-8326-102eb7307180' #UUID of policy-page for /sites/site1
    #   site2: '454d85b6-289b-11e9-b210-d663bd873d93' #UUID of policy-page for /sites/site2

    translations:
      package: 'KaufmannDigital.CookieConsent'
      source: 'Main'
    position: 'bottom'
    static: false
    theme: 'block'
    layout: 'basic'
    palette:
      popup:
        background: '#000'
        text: '#fff'
      button:
        background: '#f1d600'
        text: '#000'
    elements:
      header: '<span class="cc-header">{{header}}</span>&nbsp;'
      message: '<span id="cookieconsent:desc" class="cc-message">{{message}}</span>'
      messagelink: '<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_blank">{{link}}</a></span>'
      dismiss: '<a aria-label="dismiss cookie message" tabindex="0" class="cc-btn cc-dismiss">{{dismiss}}</a>'
      allow: '<a aria-label="allow cookies" tabindex="0" class="cc-btn cc-allow">{{allow}}</a>'
      deny: '<a aria-label="deny cookies" tabindex="0" class="cc-btn cc-deny">{{deny}}</a>'
      link: '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_blank">{{link}}</a>'
      close: '<span aria-label="dismiss cookie message" tabindex="0" class="cc-close">{{close}}</span>'
    compliance:
      'info': '<div class="cc-compliance">{{dismiss}}</div>'
      'opt-in': '<div class="cc-compliance cc-highlight">{{dismiss}}{{allow}}</div>'
      'opt-out': '<div class="cc-compliance cc-highlight">{{deny}}{{dismiss}}</div>'
    cookie:
      name: 'cookieconsent_status'
      path: '/'
      domain: ''
      expiryDays: 365
      secure: false
