Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.CookieConsent: true

KaufmannDigital:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    type: ''

    #Global configuration of PolicyPage
    policyPageNode: 'c7a91aa8-fbac-4c24-8326-102eb7307180' #UUID of global page you want to link

    #Configuration per site for multisite installations
    #Replace site1/site2 with your sitename (/sites/sitename/node-a2ufd/.../)
    policyPageNodes:
      site1: 'c7a91aa8-fbac-4c24-8326-102eb7307180' #UUID of policy-page for /sites/site1
      site2: '454d85b6-289b-11e9-b210-d663bd873d93' #UUID of policy-page for /sites/site2

    translations:
      package: 'KaufmannDigital.CookieConsent'
      source: 'Main'
    position: 'bottom'
    static: false
    theme: 'block'
    palette:
      popup:
        background: '#000'
        text: '#fff'
      button:
        background: '#f1d600'
        text: '#000'
